@echo off
echo import axios from "axios"; > "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo const BASE_URL = import.meta.env.VITE_API_URL || ""; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo export const api = axios.create({ >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   baseURL: BASE_URL + "/api", >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   withCredentials: true, >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   headers: { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     "Content-Type": "application/json" >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   } >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo }); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo api.interceptors.request.use((config) => { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   const token = localStorage.getItem("access_token"); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   if (token) { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     config.headers.Authorization = "Bearer " + token; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   } >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   return config; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo }); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo api.interceptors.response.use( >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   (response) => response, >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   async (error) => { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     const original = error.config; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     if (error.response.status === 401 && !original._retry) { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo       original._retry = true; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo       try { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo         await axios.post(BASE_URL + "/api/auth/refresh", {}, { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo           withCredentials: true >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo         }); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo         return api(original); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo       } catch { >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo         window.location.href = "/login"; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo       } >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     } >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo     return Promise.reject(error); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo   } >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo ); >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
echo export default api; >> "c:\Projeto Impacto Solu??es\frontend\src\lib\api.ts"
