"""Adicionar campos tipo_calculo e valor_total_manual ao orcamento

Revision ID: 001_add_tipo_calculo
Revises: 
Create Date: 2026-05-21 04:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_tipo_calculo'
down_revision = '000_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar tipo enum primeiro
    tipo_calculo_enum = sa.Enum('automatico', 'manual', name='tipocalculoorcamento')
    tipo_calculo_enum.create(op.get_bind())
    
    # Adicionar colunas
    op.add_column('orcamentos', sa.Column('tipo_calculo', sa.Enum('automatico', 'manual', name='tipocalculoorcamento'), nullable=False, server_default='automatico'))
    op.add_column('orcamentos', sa.Column('valor_total_manual', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamentos', 'valor_total_manual')
    op.drop_column('orcamentos', 'tipo_calculo')
    # ### end Alembic commands ###
