"""Tornar usuario_id nullable em historico_acesso

Revision ID: 002_make_historico_acesso_usuario_id_nullable
Revises: 001_add_tipo_calculo
Create Date: 2026-06-04 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_make_historico_acesso_usuario_id_nullable'
down_revision = '001_add_tipo_calculo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historico_acesso', 'usuario_id',
                    existing_type=sa.String(36),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historico_acesso', 'usuario_id',
                    existing_type=sa.String(36),
                    nullable=False)
    # ### end Alembic commands ###
