"""Adicionar token_acesso_publico em orcamentos e ordens_servico

Revision ID: 003_add_token_acesso_publico
Revises: 002_make_historico_acesso_usuario_id_nullable
Create Date: 2026-06-04 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_token_acesso_publico'
down_revision = '002_make_historico_acesso_usuario_id_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('token_acesso_publico', sa.String(64), nullable=True))
    op.create_index('ix_orcamentos_token_acesso_publico', 'orcamentos', ['token_acesso_publico'], unique=True)
    
    op.add_column('ordens_servico', sa.Column('token_acesso_publico', sa.String(64), nullable=True))
    op.create_index('ix_ordens_servico_token_acesso_publico', 'ordens_servico', ['token_acesso_publico'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordens_servico_token_acesso_publico', table_name='ordens_servico')
    op.drop_column('ordens_servico', 'token_acesso_publico')
    
    op.drop_index('ix_orcamentos_token_acesso_publico', table_name='orcamentos')
    op.drop_column('orcamentos', 'token_acesso_publico')
    # ### end Alembic commands ###
