"""agenda_timezone_aware

Revision ID: 90deecf0e5c4
Revises: ede5f0fbe2e0
Create Date: 2026-06-07 22:25:13.558211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90deecf0e5c4'
down_revision = 'ede5f0fbe2e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
