# Estágio 1: Build do frontend
FROM node:20-alpine AS frontend_builder
WORKDIR /app
COPY ../frontend/package*.json ./
RUN npm ci --frozen-lockfile
COPY ../frontend .
RUN npm run build

# Estágio 2: Nginx com build estático
FROM nginx:1.25-alpine
COPY --from=frontend_builder /app/dist /usr/share/nginx/html
RUN rm /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh && rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.e2e.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
