lines = [
    "import axios from 'axios'",
    "",
    "const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'",
    "",
    "",
    "const api = axios.create({",
    "  baseURL: API_URL,",
    "  headers: {",
    "    'Content-Type': 'application/json',",
    "  },",
    "})",
    "",
    "",
    "api.interceptors.request.use(",
    "  (config) => {",
    "    const token = localStorage.getItem('access_token')",
    "    if (token) {",
    "      config.headers.Authorization = `Bearer ${token}`",
    "    }",
    "    return config",
    "  },",
    "  (error) => {",
    "    return Promise.reject(error)",
    "  }",
    ")",
    "",
    "",
    "api.interceptors.response.use(",
    "  (response) => response,",
    "  async (error) => {",
    "    if (error.response?.status === 401) {",
    "      localStorage.removeItem('access_token')",
    "      localStorage.removeItem('refresh_token')",
    "      window.location.href = '/login'",
    "    }",
    "    return Promise.reject(error)",
    "  }",
    ")",
    "",
    "",
    "export default api"
]

with open(r'c:\Projeto Impacto Soluções\frontend\src\lib\api.ts', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print("Arquivo corrigido com sucesso")
